#!/usr/bin/env python

# Variables for 'waf dist'
APPNAME = 'sorcer.lv2'
VERSION = '1.0.0'

# Mandatory variables
top = '.'
out = 'build'

def options(opt):
    opt.load('compiler_c')
    opt.load('compiler_cxx')

def configure(ctx):
    ctx.load('compiler_c')
    ctx.load('compiler_cxx')
    
    print('Sorcer Configuration')

    if ctx.env['MSVC_COMPILER']:
        ctx.env.append_unique('CFLAGS', ['-TP', '-MD'])
    else:
        ctx.env.append_unique('CFLAGS', '-std=c99')
    
    # faust include and fast math 
    #'-g', '-pg',
    ctx.env.CXXFLAGS = ['-I/usr/lib/faust/','-I/usr/lib/faust/gui','-Wall','-O3','-ffast-math']
    
    # Check for gtkmm to build UI, sndfile for loading
    ctx.check_cfg(package='gtkmm-2.4',at_least_version='1.0',args='--cflags --libs',uselib_store='GTKMM')
    ctx.check_cfg(package='lv2',at_least_version='1.0',args='--cflags --libs',uselib_store='LV2')
    
    # Set env['pluginlib_PATTERN']
    pat = ctx.env['cshlib_PATTERN']
    if pat.startswith('lib'):
        pat = pat[3:]
    ctx.env['pluginlib_PATTERN'] = pat
    ctx.env['pluginlib_EXT'] = pat[pat.rfind('.'):]

    #print("LV2 bundle directory", ctx.env['LV2DIR'])
    #print('')

def build(ctx):
    bundle = APPNAME
    
    includes = ''
    
    # Build plugin UI library
    obj = ctx(features     = 'cxx cxxshlib',
              source       = 'canvas.cxx sorcer_gui.cxx',
              name         = 'sorcer_gui',
              target       = 'sorcer_gui',
              uselib       = 'GTKMM LV2',
              includes     = includes)

